name = "y-router"
main = "index.ts"
compatibility_date = "2025-05-30"

# Enable logging
[observability]
enabled = true
head_sampling_rate = 1

[vars]
OPENROUTER_BASE_URL = "https://api.openai.com/v1"
